# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.6.2
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-12-17T12:03:53Z"
  labels:
    app: db-pod
  name: db-pod
spec:
  containers:
  - args:
    - run-postgresql
    env:
    - name: POSTGRESQL_DATABASE
      value: djdb
    - name: POSTGRESQL_USER
      value: djuser
    - name: POSTGRESQL_PASSWORD
      value: djpassword
    image: registry.redhat.io/rhel9/postgresql-15:latest
    name: db
    securityContext:
      runAsNonRoot: true

