# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.6.2

# NOTE: The namespace sharing for a pod has been modified by the user and is not the same as the
# default settings for kubernetes. This can lead to unexpected behavior when running the generated
# kube yaml in a kubernetes cluster.
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.SandboxID/setreq-dbdb1: a04c7cff24b73db8ad327503dd2a549e7617ef6822b84441fdb8a437669c99ee
    io.kubernetes.cri-o.SandboxID/setreq-dbfrontend1: a04c7cff24b73db8ad327503dd2a549e7617ef6822b84441fdb8a437669c99ee
    io.kubernetes.cri-o.SandboxID/setreq-dbrequest-service1: a04c7cff24b73db8ad327503dd2a549e7617ef6822b84441fdb8a437669c99ee
  creationTimestamp: "2025-12-16T01:11:35Z"
  labels:
    app: podsetreq-db
  name: podsetreq-db
spec:
  containers:
  - args:
    - run-postgresql
    env:
    - name: POSTGRESQL_DATABASE
      value: djdb
    - name: POSTGRESQL_USER
      value: djuser
    - name: POSTGRESQL_PASSWORD
      value: djpassword
    image: registry.redhat.io/rhel9/postgresql-15:latest
    name: setreq-dbdb1
    ports:
    - containerPort: 5432
      hostPort: 5432
    securityContext:
      runAsNonRoot: true
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: setreq-db-postgres-data-pvc
  - args:
    - uvicorn
    - app.main:app
    - --host
    - 0.0.0.0
    - --port
    - "8000"
    env:
    - name: DATABASE_URL
      value: postgresql://djuser:djpassword@db:5432/djdb
    image: localhost/setreq-db_request-service:latest
    name: setreq-dbrequest-service1
    ports:
    - containerPort: 8000
      hostPort: 8000
    securityContext:
      runAsNonRoot: true
  - args:
    - /usr/sbin/nginx
    - -g
    - daemon off;
    image: localhost/setreq-db_frontend:latest
    name: setreq-dbfrontend1
    ports:
    - containerPort: 8080
      hostPort: 3000
    securityContext:
      runAsNonRoot: true
  volumes:
  - name: setreq-db-postgres-data-pvc
    persistentVolumeClaim:
      claimName: setreq-db-postgres-data

